var annotated_dup =
[
    [ "SystemMiami", "namespace_system_miami.html", [
      [ "AbilitySystem", "namespace_system_miami_1_1_ability_system.html", [
        [ "Abilities", "class_system_miami_1_1_ability_system_1_1_abilities.html", null ],
        [ "Ability", "class_system_miami_1_1_ability_system_1_1_ability.html", null ]
      ] ],
      [ "CombatRefactor", "namespace_system_miami_1_1_combat_refactor.html", [
        [ "AbilityMagical", "class_system_miami_1_1_combat_refactor_1_1_ability_magical.html", null ],
        [ "AbilityPhysical", "class_system_miami_1_1_combat_refactor_1_1_ability_physical.html", null ],
        [ "ActionConfirmation", "class_system_miami_1_1_combat_refactor_1_1_action_confirmation.html", "class_system_miami_1_1_combat_refactor_1_1_action_confirmation" ],
        [ "ActionEquipped", "class_system_miami_1_1_combat_refactor_1_1_action_equipped.html", "class_system_miami_1_1_combat_refactor_1_1_action_equipped" ],
        [ "ActionExecution", "class_system_miami_1_1_combat_refactor_1_1_action_execution.html", "class_system_miami_1_1_combat_refactor_1_1_action_execution" ],
        [ "ActionQuickslot", "class_system_miami_1_1_combat_refactor_1_1_action_quickslot.html", null ],
        [ "ActionSelection", "class_system_miami_1_1_combat_refactor_1_1_action_selection.html", "class_system_miami_1_1_combat_refactor_1_1_action_selection" ],
        [ "CombatAction", "class_system_miami_1_1_combat_refactor_1_1_combat_action.html", "class_system_miami_1_1_combat_refactor_1_1_combat_action" ],
        [ "CombatActionSO", "class_system_miami_1_1_combat_refactor_1_1_combat_action_s_o.html", null ],
        [ "CombatantState", "class_system_miami_1_1_combat_refactor_1_1_combatant_state.html", "class_system_miami_1_1_combat_refactor_1_1_combatant_state" ],
        [ "CombatantStateFactory", "class_system_miami_1_1_combat_refactor_1_1_combatant_state_factory.html", null ],
        [ "CombatantStateMachine", "class_system_miami_1_1_combat_refactor_1_1_combatant_state_machine.html", null ],
        [ "Consumable", "class_system_miami_1_1_combat_refactor_1_1_consumable.html", null ],
        [ "ConsumableSO", "class_system_miami_1_1_combat_refactor_1_1_consumable_s_o.html", null ],
        [ "Dead", "class_system_miami_1_1_combat_refactor_1_1_dead.html", "class_system_miami_1_1_combat_refactor_1_1_dead" ],
        [ "Dying", "class_system_miami_1_1_combat_refactor_1_1_dying.html", "class_system_miami_1_1_combat_refactor_1_1_dying" ],
        [ "EnemyActionConfirmation", "class_system_miami_1_1_combat_refactor_1_1_enemy_action_confirmation.html", null ],
        [ "EnemyActionEquipped", "class_system_miami_1_1_combat_refactor_1_1_enemy_action_equipped.html", null ],
        [ "EnemyActionSelection", "class_system_miami_1_1_combat_refactor_1_1_enemy_action_selection.html", null ],
        [ "EnemyDead", "class_system_miami_1_1_combat_refactor_1_1_enemy_dead.html", null ],
        [ "EnemyDying", "class_system_miami_1_1_combat_refactor_1_1_enemy_dying.html", null ],
        [ "EnemyIdle", "class_system_miami_1_1_combat_refactor_1_1_enemy_idle.html", null ],
        [ "EnemyMovementConfirmation", "class_system_miami_1_1_combat_refactor_1_1_enemy_movement_confirmation.html", "class_system_miami_1_1_combat_refactor_1_1_enemy_movement_confirmation" ],
        [ "EnemyMovementTileSelection", "class_system_miami_1_1_combat_refactor_1_1_enemy_movement_tile_selection.html", null ],
        [ "EnemyTurnEnd", "class_system_miami_1_1_combat_refactor_1_1_enemy_turn_end.html", null ],
        [ "EnemyTurnStart", "class_system_miami_1_1_combat_refactor_1_1_enemy_turn_start.html", "class_system_miami_1_1_combat_refactor_1_1_enemy_turn_start" ],
        [ "Idle", "class_system_miami_1_1_combat_refactor_1_1_idle.html", "class_system_miami_1_1_combat_refactor_1_1_idle" ],
        [ "ITargetable", "interface_system_miami_1_1_combat_refactor_1_1_i_targetable.html", null ],
        [ "Loadout", "class_system_miami_1_1_combat_refactor_1_1_loadout.html", null ],
        [ "MovementConfirmation", "class_system_miami_1_1_combat_refactor_1_1_movement_confirmation.html", "class_system_miami_1_1_combat_refactor_1_1_movement_confirmation" ],
        [ "MovementExecution", "class_system_miami_1_1_combat_refactor_1_1_movement_execution.html", "class_system_miami_1_1_combat_refactor_1_1_movement_execution" ],
        [ "MovementTileSelection", "class_system_miami_1_1_combat_refactor_1_1_movement_tile_selection.html", "class_system_miami_1_1_combat_refactor_1_1_movement_tile_selection" ],
        [ "NewAbility", "class_system_miami_1_1_combat_refactor_1_1_new_ability.html", null ],
        [ "NewAbilitySO", "class_system_miami_1_1_combat_refactor_1_1_new_ability_s_o.html", null ],
        [ "PlayerActionConfirmation", "class_system_miami_1_1_combat_refactor_1_1_player_action_confirmation.html", null ],
        [ "PlayerActionSelection", "class_system_miami_1_1_combat_refactor_1_1_player_action_selection.html", "class_system_miami_1_1_combat_refactor_1_1_player_action_selection" ],
        [ "PlayerCombatantStateMachine", "class_system_miami_1_1_combat_refactor_1_1_player_combatant_state_machine.html", null ],
        [ "PlayerDead", "class_system_miami_1_1_combat_refactor_1_1_player_dead.html", null ],
        [ "PlayerDying", "class_system_miami_1_1_combat_refactor_1_1_player_dying.html", null ],
        [ "PlayerIdle", "class_system_miami_1_1_combat_refactor_1_1_player_idle.html", null ],
        [ "PlayerMovementConfirmation", "class_system_miami_1_1_combat_refactor_1_1_player_movement_confirmation.html", null ],
        [ "PlayerMovementTileSelection", "class_system_miami_1_1_combat_refactor_1_1_player_movement_tile_selection.html", null ],
        [ "PlayerTurnEnd", "class_system_miami_1_1_combat_refactor_1_1_player_turn_end.html", null ],
        [ "PlayerTurnStart", "class_system_miami_1_1_combat_refactor_1_1_player_turn_start.html", "class_system_miami_1_1_combat_refactor_1_1_player_turn_start" ],
        [ "TurnEnd", "class_system_miami_1_1_combat_refactor_1_1_turn_end.html", "class_system_miami_1_1_combat_refactor_1_1_turn_end" ],
        [ "TurnStart", "class_system_miami_1_1_combat_refactor_1_1_turn_start.html", "class_system_miami_1_1_combat_refactor_1_1_turn_start" ]
      ] ],
      [ "CombatSystem", "namespace_system_miami_1_1_combat_system.html", [
        [ "AreaOfEffectPattern", "class_system_miami_1_1_combat_system_1_1_area_of_effect_pattern.html", "class_system_miami_1_1_combat_system_1_1_area_of_effect_pattern" ],
        [ "Combatant", "class_system_miami_1_1_combat_system_1_1_combatant.html", "class_system_miami_1_1_combat_system_1_1_combatant" ],
        [ "CombatantDecisions", "class_system_miami_1_1_combat_system_1_1_combatant_decisions.html", null ],
        [ "CombatSubaction", "class_system_miami_1_1_combat_system_1_1_combat_subaction.html", null ],
        [ "Damage", "class_system_miami_1_1_combat_system_1_1_damage.html", null ],
        [ "DebugCombatAction", "class_system_miami_1_1_combat_system_1_1_debug_combat_action.html", null ],
        [ "EnemyCombatant", "class_system_miami_1_1_combat_system_1_1_enemy_combatant.html", null ],
        [ "ForceMovement", "class_system_miami_1_1_combat_system_1_1_force_movement.html", null ],
        [ "Heal", "class_system_miami_1_1_combat_system_1_1_heal.html", null ],
        [ "InflictPercentStatusEffect", "class_system_miami_1_1_combat_system_1_1_inflict_percent_status_effect.html", null ],
        [ "InflictStatusEffect", "class_system_miami_1_1_combat_system_1_1_inflict_status_effect.html", null ],
        [ "PlayerCombatant", "class_system_miami_1_1_combat_system_1_1_player_combatant.html", "class_system_miami_1_1_combat_system_1_1_player_combatant" ],
        [ "PlayerDecisions", "class_system_miami_1_1_combat_system_1_1_player_decisions.html", null ],
        [ "SingleTilePattern", "class_system_miami_1_1_combat_system_1_1_single_tile_pattern.html", null ],
        [ "TargetingPattern", "class_system_miami_1_1_combat_system_1_1_targeting_pattern.html", "class_system_miami_1_1_combat_system_1_1_targeting_pattern" ]
      ] ],
      [ "Interfaces", "namespace_system_miami_1_1_interfaces.html", [
        [ "ITileOccupier", "interface_system_miami_1_1_interfaces_1_1_i_tile_occupier.html", null ]
      ] ],
      [ "ui", "namespace_system_miami_1_1ui.html", [
        [ "AbilityBar", "class_system_miami_1_1ui_1_1_ability_bar.html", null ],
        [ "AbilitySlot", "class_system_miami_1_1ui_1_1_ability_slot.html", null ],
        [ "UnequipPrompt", "class_system_miami_1_1ui_1_1_unequip_prompt.html", null ]
      ] ],
      [ "AbilityDirections", "class_system_miami_1_1_ability_directions.html", null ],
      [ "AnimationClipOverrides", "class_system_miami_1_1_animation_clip_overrides.html", null ],
      [ "EnemyCombatantStateMachine", "class_system_miami_1_1_enemy_combatant_state_machine.html", null ],
      [ "EnemyDamage", "class_system_miami_1_1_enemy_damage.html", null ],
      [ "EnemyDecisions", "class_system_miami_1_1_enemy_decisions.html", null ],
      [ "IDamageable", "interface_system_miami_1_1_i_damageable.html", null ],
      [ "IHealable", "interface_system_miami_1_1_i_healable.html", null ],
      [ "IMovable", "interface_system_miami_1_1_i_movable.html", null ],
      [ "PlayerActionEquipped", "class_system_miami_1_1_player_action_equipped.html", null ],
      [ "RestoreResource", "class_system_miami_1_1_restore_resource.html", null ],
      [ "Targets", "class_system_miami_1_1_targets.html", null ],
      [ "TileContext", "struct_system_miami_1_1_tile_context.html", null ],
      [ "TurnManager", "class_system_miami_1_1_turn_manager.html", null ]
    ] ]
];